# Generated by Django 6.0.2 on 2026-02-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен для работы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driver_license',
            field=models.CharField(blank=True, max_length=100, verbose_name='Водительское удостоверение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_categories',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категории (например: B, C, CE)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_routes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предпочитаемые маршруты'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки и умения'),
        ),
    ]
