# Generated by Django 6.0.2 on 2026-02-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_available_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('busy', 'Занят')], default='available', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_entries', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Доступность водителя',
                'verbose_name_plural': 'Доступность водителей',
                'ordering': ['start_date'],
            },
        ),
    ]
