# Generated by Django 6.0.2 on 2026-02-08 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driveravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('punctuality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Пунктуальность')),
                ('professionalism', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Профессионализм')),
                ('communication', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Коммуникация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'trucker'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.userprofile')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Рейтинг водителя',
                'verbose_name_plural': 'Рейтинги водителей',
                'ordering': ['-created_at'],
                'unique_together': {('driver', 'rated_by')},
            },
        ),
    ]
